# Generated by Django 3.1.1 on 2020-10-06 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conf_room',
            fields=[
                ('ID_room', models.CharField(default='O0MG4A', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('wait_status', models.BooleanField(default=True)),
                ('open_status', models.BooleanField(default=True)),
                ('time_out', models.IntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='User_session',
            fields=[
                ('ID_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ID_room', models.ManyToManyField(to='chat.Conf_room')),
            ],
        ),
    ]
