# Generated by Django 3.1.1 on 2020-10-06 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_room',
            name='ID_room',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_session',
            name='ID_user',
            field=models.UUIDField(default=uuid.UUID('d59ea07a-a7cd-4dea-9a5d-9ecf0eda3c2f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
