# Generated by Django 3.1.1 on 2020-10-06 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201006_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_session',
            name='ID_user',
            field=models.UUIDField(default=uuid.UUID('feb6a347-8edc-4412-b8b7-e9e427a356aa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
