# Generated by Django 3.1.1 on 2020-10-06 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201006_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_session',
            name='ID_user',
            field=models.UUIDField(default=uuid.UUID('4075c2b0-3e3e-49dc-aefa-438f794fadf2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
