# Generated by Django 3.1.1 on 2020-10-06 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201006_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfRoom',
            fields=[
                ('ID_room', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('wait_status', models.BooleanField(default=True)),
                ('open_status', models.BooleanField(default=True)),
                ('time_out', models.IntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('ID_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ID_room', models.ManyToManyField(to='chat.ConfRoom')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_session',
            name='ID_room',
        ),
        migrations.DeleteModel(
            name='Conf_room',
        ),
        migrations.DeleteModel(
            name='User_session',
        ),
    ]
