# Generated by Django 3.1.1 on 2020-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201006_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default=0, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
