# Generated by Django 3.1.1 on 2020-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20201006_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='I1GYS7F2CE', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='241dec01-9186-42a5-b130-37ad7494d5b5', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
