# Generated by Django 3.1.1 on 2020-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20201006_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='Z6NIU8OR64', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='167790f2-ff77-4b97-8106-70279c40b8ae', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
