# Generated by Django 3.1.1 on 2020-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20201006_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='A132ZSYDJD', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='20c62261-0d24-4e9b-8e50-05066e64e6eb', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
