# Generated by Django 3.1.1 on 2020-10-06 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20201006_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='Z1E75F1X7R', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default=uuid.UUID('609029c5-5b72-424a-a56f-4fe98b27469e'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
