# Generated by Django 3.1.1 on 2020-10-06 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20201006_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='X76DZOHTJY', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default=uuid.UUID('8f48f6a8-0820-482d-9303-a6cd7feb2b5c'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
