# Generated by Django 3.1.1 on 2020-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20201006_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='94OHR7H8RT', max_length=20, primary_key=True, serialize=False),
        ),
    ]
