# Generated by Django 3.1.1 on 2020-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20201006_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='O2LR0JNXBL', max_length=20, primary_key=True, serialize=False),
        ),
    ]
