# Generated by Django 3.1.1 on 2020-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20201006_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='4RRSOL8J2W', max_length=20, primary_key=True, serialize=False),
        ),
    ]
