# Generated by Django 3.1.1 on 2020-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20201006_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='V9VLO3C5G7', max_length=20, primary_key=True, serialize=False),
        ),
    ]
