# Generated by Django 3.1.1 on 2020-10-06 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20201006_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='KV1FYQK1VA', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.UUIDField(default=uuid.UUID('5ca78823-f390-448a-a0c4-3adae298ed1b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
