# Generated by Django 3.1.1 on 2020-10-06 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20201006_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='SGFM2DM05I', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default=uuid.UUID('2d7613e5-57d1-45b0-8e53-d9032e2c68de'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
