# Generated by Django 3.1.1 on 2020-10-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20201006_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='1BBHM5SV6H', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='97b38458-e1d7-46b2-8313-c337f420bbc3', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
