# Generated by Django 3.1.1 on 2020-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20201006_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='E7OHFKB3XX', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='54e33b68-1c9c-4303-90ed-82c223c29705', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
