# Generated by Django 3.1.1 on 2020-10-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_auto_20201006_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='X74Q9BTSI6', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='c54bc66d-d0e8-44e1-8a4d-e49aef802c50', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
