# Generated by Django 3.1.1 on 2020-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_auto_20201007_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='AX0JQITF8U', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='c1fd01cc-e005-4724-b24b-338826140927', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
