# Generated by Django 3.1.1 on 2020-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_auto_20201007_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBaseMethods',
        ),
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='8JRC4KKBJF', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='35be5660-9785-41a5-a5c8-f83b1ea4f5a1', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
