# Generated by Django 3.1.1 on 2020-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_auto_20201008_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='85KO1LTAUP', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='9b6eb776-6709-47d9-9001-c67474155f08', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
