# Generated by Django 3.1.1 on 2020-10-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_auto_20201008_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='NUO4HK4C13', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='05f209d9-3626-4219-adbd-2e757c80a709', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
