# Generated by Django 3.1.1 on 2020-10-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_auto_20201008_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='A7V689TJPJ', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='6b46ed6f-ef54-40b4-a447-77ef14f8d720', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
