# Generated by Django 3.1.1 on 2020-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_auto_20201008_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='JY7RGJLYXJ', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='71a28952-1fa1-40c3-8a8a-6f97864dda76', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
