# Generated by Django 3.1.1 on 2020-10-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_auto_20201009_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='9PNO1SJU8Y', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='4a1fcb92-4613-4216-84ae-6be108e3ef33', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
