# Generated by Django 3.1.1 on 2020-10-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_auto_20201009_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='VOEN6SWHAX', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='dff4ba37-6548-4de0-9ab5-e960d253c268', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
