# Generated by Django 3.1.1 on 2020-10-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_auto_20201009_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='1X60CGVYOF', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ID_user',
            field=models.CharField(default='308e9170-b466-4c36-a85f-d2c9055a84d2', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
