# Generated by Django 3.1.1 on 2020-10-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_auto_20201010_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='3W4O6ACNC2', max_length=20, primary_key=True, serialize=False),
        ),
    ]
