# Generated by Django 3.1.1 on 2020-10-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_auto_20201010_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='1K3GGU46IX', max_length=20, primary_key=True, serialize=False),
        ),
    ]
