# Generated by Django 3.1.1 on 2020-10-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_auto_20201012_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='ASK4CRPQH7', max_length=20, primary_key=True, serialize=False),
        ),
    ]
