# Generated by Django 3.1.1 on 2020-10-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_auto_20201012_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='LYCH6JCEKW', max_length=20, primary_key=True, serialize=False),
        ),
    ]
