# Generated by Django 3.1.1 on 2020-10-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_auto_20201012_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='ID_room',
            field=models.CharField(default='7YUHR63G9V', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='confroom',
            name='wait_status',
            field=models.BooleanField(),
        ),
    ]
